=== kandurisripaada/wt/po/bookstore.dtd
<!ELEMENT bookstore (book+)>
<!ELEMENT book (title, author, year, publisher, price)>
<!ATTLIST book category CDATA #REQUIRED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== kandurisripaada/wt/po/book1xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore SYSTEM "bookstore.dtd">

<bookstore>
    <book category="fiction">
        <title>The Great Gatsby</title>
        <author>F. Scott Fitzgerald</author>
        <year>1925</year>
        <publisher>Scribner</publisher>
        <price>10.99</price>
    </book>
    
    <book category="programming">
        <title>Learning XML</title>
        <author>Erik T. Ray</author>
        <year>2003</year>
        <publisher>O'Reilly Media</publisher>
        <price>39.95</price>
    </book>
</bookstore>
